// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS6wFyMIeN4vwp1oNv-LYnoxr0FeLbyWg',
    appId: '1:418451525572:web:7f51d2ac741fb5bf085e91',
    messagingSenderId: '418451525572',
    projectId: 'solar-panels-6134a',
    authDomain: 'solar-panels-6134a.firebaseapp.com',
    storageBucket: 'solar-panels-6134a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxaR8fRhL03SkB7bIZHGja1M-D9H8-6mA',
    appId: '1:418451525572:android:e70970cd13803fe9085e91',
    messagingSenderId: '418451525572',
    projectId: 'solar-panels-6134a',
    storageBucket: 'solar-panels-6134a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGRxjhXSepV-ZJfWjBtxMX3qBqCHLBook',
    appId: '1:418451525572:ios:941228961b6d1cb5085e91',
    messagingSenderId: '418451525572',
    projectId: 'solar-panels-6134a',
    storageBucket: 'solar-panels-6134a.firebasestorage.app',
    iosClientId: '418451525572-qld9gmah3u9eve89p7tj2eh1fdehmoid.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGRxjhXSepV-ZJfWjBtxMX3qBqCHLBook',
    appId: '1:418451525572:ios:941228961b6d1cb5085e91',
    messagingSenderId: '418451525572',
    projectId: 'solar-panels-6134a',
    storageBucket: 'solar-panels-6134a.firebasestorage.app',
    iosClientId: '418451525572-qld9gmah3u9eve89p7tj2eh1fdehmoid.apps.googleusercontent.com',
    iosBundleId: 'com.example.solarClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS6wFyMIeN4vwp1oNv-LYnoxr0FeLbyWg',
    appId: '1:418451525572:web:154dcd18dee6e23e085e91',
    messagingSenderId: '418451525572',
    projectId: 'solar-panels-6134a',
    authDomain: 'solar-panels-6134a.firebaseapp.com',
    storageBucket: 'solar-panels-6134a.firebasestorage.app',
  );
}
